-
  name:                Instalacja Xwiki na Ubuntu
  hosts:               ansible002
  tasks:
    - name:            Update Repozytorium maven.xwiki.org
      apt_key:
        url:           https://maven.xwiki.org/public.gpg
        state:         present
      become:          true
    - name:            Update Repozytorium xwiki-stable.list
      get_url:
        url:           https://maven.xwiki.org/stable/xwiki-stable.list
        dest:          /etc/apt/sources.list.d/xwiki-stable.list
      become:          true
    - name:            Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache:  yes
      become:          true
    - name:            Installacja wymaganych komponentow
      apt:
        name:          "{{ item }}"
        state:         present
      with_items:
        - screen
        - xwiki-tomcat9-common
        - xwiki-pgsql-common
        - xwiki-tomcat9-pgsql
      become:          true

    - name:            Create a symbolic link /bin/catalina.sh
      file:
        src:           /usr/share/tomcat9/bin/catalina.sh
        dest:          /bin/catalina.sh
        owner:         root
        group:         root
        state:         link
      become:          true

    - name:            Create a directory /usr/share/tomcat9/conf
      file:
        path:          /usr/share/tomcat9/conf
        state:         directory
        mode:          '0755'
      become:          true

    - name:            Create a symbolic link /usr/share/tomcat9/conf/server.xml
      file:
        src:           /etc/tomcat9/server.xml
        dest:          /usr/share/tomcat9/conf/server.xml
        owner:         root
        group:         root
        state:         link
      become:          true

    - name:            Create a symbolic link /usr/share/tomcat9/conf/tomcat-users.xml
      file:
        src:           /etc/tomcat9/tomcat-users.xml
        dest:          /usr/share/tomcat9/conf/tomcat-users.xml
        owner:         root
        group:         root
        state:         link
      become:          true

    - name:            Copy xwiki.cfg
      copy:
        src:           ./Files/xwiki.cfg
        dest:          /etc/xwiki/xwiki.cfg
        owner:         root
        group:         root
        mode:          '0644'
      become:          true

    - name:            Copy tomcat9
      copy:
        src:           ./Files/tomcat9
        dest:          /etc/default/tomcat9
        owner:         root
        group:         root
        mode:          '0644'
      become:          true

    - name:            Enable tomcat startup
      systemd:
        name:          tomcat9
        enabled:       yes
        daemon_reload: yes
        become:        true
