-
  name:                Instalacja Xwiki na Ubuntu
  hosts:               ansible002
  remote_user:         root
  become:              yes
  tasks:

 ## Instalacja Servera Tomcat 9.0.30

    - name:            Set JAVA_HOME
      lineinfile:
        dest:          /etc/environment
        state:         present
        regexp:        '^JAVA_HOME'
        line:          'JAVA_HOME=/usr/lib/jvm/java-13-openjdk-amd64'

    - name:            Repo Oracle Java JDK 8
      apt_repository:
        repo:          ppa:webupd8team/java
        state:         present

    - name:            Installacja wymaganych komponentow
      apt:
        update_cache:  yes
        name:          "{{ item }}"
        state:         present
      with_items:
        - openjdk-13-jdk
        - htop
        - screen
        - nmon
        - iftop
        #- libreoffice
        - unzip
        - procps
        - curl
        - python-psycopg2
        - libpq-dev

    - name:            Download Tomcat 9
      get_url:
        url:           http://ftp.man.poznan.pl/apache/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
        dest:          /opt/tomcat9.tar.gz
        mode:          '0744'

    - name:            Extract Tomcat 9
      unarchive:
        src:           /opt/tomcat9.tar.gz
        dest:          /opt/

    - name:            Copy /etc/systemd/system/tomcat.service
      copy:
        src:           ./Files/tomcat.service
        dest:          /etc/systemd/system/tomcat.service
        mode:          0644


    - name:            Start and enable Tomcat service
      systemd:
        name:          tomcat
        state:         restarted
        enabled:       true
        daemon_reload: true
      become:          true

    - name:            Download Xwiki
      get_url:
        url:           https://maven.xwiki.org/releases/org/xwiki/platform/xwiki-platform-distribution-war/12.0-rc-1/xwiki-platform-distribution-war-12.0-rc-1.war
        dest:          /opt/xwiki.war
        mode:          '0744'

    - name:            Extract xwiki.war to tomcat ROOT
      unarchive:
        src:           /opt/xwiki.war
        dest:          /opt/apache-tomcat-9.0.30/webapps/ROOT

## Instalacja Postgresql i Xwiki

    - name:            Update Repozytorium maven.xwiki.org
      apt_key:
        url:           https://maven.xwiki.org/public.gpg
        state:         present
    - name:            Update Repozytorium xwiki-stable.list
      get_url:
        url:           https://maven.xwiki.org/stable/xwiki-stable.list
        dest:          /etc/apt/sources.list.d/xwiki-stable.list
    - name:            Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache:  yes
    - name:            Installacja wymaganych komponentow
      apt:
        name:          "{{ item }}"
        state:         present
      with_items:
        - xwiki-pgsql-common
        - xwiki-tomcat9-pgsql
        - libpostgresql-jdbc-java

    - name:            Copy the JDBC driver in the XWiki webapp
      copy:
        src:           /usr/share/java/postgresql-jdbc4.jar
        dest:          /opt/apache-tomcat-9.0.30/webapps/ROOT/WEB-INF/lib
        mode:          0644

    - name:            Copy hibernate.cfg.xml
      copy:
        src:           ./Files/hibernate.cfg.xml
        dest:          /opt/apache-tomcat-9.0.30/webapps/ROOT/WEB-INF
        mode:          0644


    - name:            Copy pg_hba.conf
      copy:
        src:           ./Files/pg_hba.conf
        dest:          /etc/postgresql/11/main
        mode:          0644

    - name:            Restart service postgresql, in all cases
      service:
        name:          postgresql
        state:         restarted

## Create database grant

    - name:            Create a new database with name "xwiki"
      #become:         yes
      #become_user:    postgres
      postgresql_db:
        name:          xwiki
      ignore_errors:   yes

    #- name:           Connect to test database, remove xwiki user
    #  postgresql_user:
    #    db:           xwiki
    #    name:         xwiki
    #    priv:         ALL
    #    state:        absent

    - name:            Connect to xwiki database and set user's password with no expire date
      command:         sudo -u postgres bash -c "psql -c \"CREATE USER xwiki PASSWORD 'xwiki' VALID UNTIL 'infinity';\""
      ignore_errors:   yes

    - name:            ADD GRANT to xwiki DB
      command:         sudo -u postgres bash -c "psql -c \"GRANT ALL ON SCHEMA public TO xwiki;\""
      ignore_errors:   yes
